//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResumeProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSkill
    {
        public int SkillID { get; set; }
        public string SkillTitle { get; set; }
        public string SkillDescription { get; set; }
        public string SkillIcon { get; set; }
    }
}
